### ISSUE TITLE
Latex completion not working on Linux

### ISSUE THREAD

**Issue by staticfloat** [JuliaEditorSupport/julia-vscode#163]
I have a functional vscode + julia setup, except my latex completions don't seem to be working.  This is the case for both Julia 0.6.0-rc2 and Julia 0.5.2.  How can I debug this?

When I type, e.g. `\nu`, there are no completions that come up.  I do get completions for other words defined within my file, and I can `CTRL-ENTER` to run julia code, but there doesn't seem to be any communication between vscode and julia about the text within the editor.

**Comment by ZacLN** [comment]
Hi, this is a known problem and is fixed on master. The next release (with fix + other features) should be ready to be tagged soon or if you don't mind a bit of fiddling you can checkout the master version of `julia-vscode` (possibly with a `git submodule update`.

**Comment by staticfloat** [comment]
Great, how might I check it out?  I tried deleting the `~/.vscode/extensions/julialang-language-julia-0.5.1` directory, cloning down this repository and putting it in the same place (after a `git submodule init && git submodule update` of course) but that doesn't seem to work; vscode notices that it's installed, but all the commands don't work.

**Comment by ZacLN** [comment]
Sorry, turns out it's slightly more complicated (and this is for 0.6.0- only)
- cd ~/.vscode/extensions
- remove julia-vscode directory
- `git clone --recursive -b lint-cmd https://github.com/ZacLN/julia-vscode julia-vscode`
- `cd julia-vscode`
- `npm install`
- `cd scripts/languageserver/packages/CSTParser`
- `git checkout master`
- `cd ..`
- `rm -rf LanguageServer`
-  `git clone -b lin-trav https://github.com/ZacLN/LanguageServer.jl LanguageServer`

That should get things up and running (slightly unstable) before the release

**Comment by staticfloat** [comment]
Hmmm, so I did that, but I still get this error when I try to start a REPL after doing that:

![screenshot from 2017-05-26 15 56 34](https://cloud.githubusercontent.com/assets/130920/26515084/e9a27700-422b-11e7-894f-8969bd31d9b2.png)

**Comment by staticfloat** [comment]
One thing I've noticed is that I don't have a `.vsixmanifest` file; is that important?

**Comment by ZacLN** [comment]
Hmm, that's weird. The startREPL command doesn't do anything special (it's just a terminal w/ julia started). If you open a `.jl` file do you get syntax highlighting/hovers?

**Comment by staticfloat** [comment]
I definitely get syntax highlighting, and VSCode shows the plugin as installed with a new version string, but none of the commands work.

I'm not sure what a "hover" is.  I get generic VSCode tab-completions, if that's what you mean.

**Comment by ZacLN** [comment]
instructions [here](https://github.com/JuliaEditorSupport/julia-vscode/commit/d2b889e1e86ee49a8ccd026969b60a71ba1a4f95#commitcomment-22320686) should work

**Comment by staticfloat** [comment]
Indeed they do.  I guess I'll leave this open until the new version is released.

**Comment by barche** [comment]
I just tried the alpha3 vsix and latex completions still didn't appear. Is that a regression or is there more to it than just installing the vsix?

**Comment by ZacLN** [comment]
It takes a little bit of time for the language server to get up and running, especially if you're opening a large project.

**Comment by davidanthoff** [comment]
I'm closing this because we think this is fixed for v0.6.0. We will have a beta out for that version today, and hopefully a release next week. If you still see this problem on v0.6.0, please report back here and I'll reopen the issue.

**Comment by chriselrod** [comment]
I have v0.7.0 and latex completions don't work on Linux.
I also get "Extension host terminated unexpectedly" errors.

**Comment by davidanthoff** [comment]
I think the root cause is that if the extension crashes, the latex completions also stop working. So really we need to fix the crash of the extension to fix this. It might all be resolved in v0.8.0, which we are beta testing right now. @chriselrod would be great if you could try with the v0.8.0 beta and see whether you get the same issue.

**Comment by chriselrod** [comment]
Not an especially scientific test, because I'm currently on another computer (running Ubuntu 17.04). I'll be back at the former on Monday (running Ubuntu 16.04).
Also not sure if there is any more to installing, but I just git cloned into .vscode/extensions. The extension shows up as Julia 0.8.0-beta, and I have syntax highlighting.
I haven't seen any "Extension host terminated unexpectedly" errors, but still no LaTeX completions.

Also no auto-indents, such as in new lines when starting loops/functions/etc. For reference, my settings (in case I messed something up there):
```
{
    "editor.tabCompletion": true,
    "editor.wordWrap": "on",
    "editor.autoIndent": true,
    "julia.executablePath":"/home/chris/Documents/programs/julia/julia"
}
```

**Comment by ZacLN** [comment]
I don't think that will gave built/installed it. Best to delete relevant dirs from .vscode/extensions and install from the vsix file

**Comment by chriselrod** [comment]
Did not work either.

**Comment by chriselrod** [comment]
Does not work beta release candidate 3.

**Comment by ZacLN** [comment]
in the extension directory are there  `node_modules` and `out` folders?

**Comment by chriselrod** [comment]
```bash
$ ls .vscode/extensions/
julialang.language-julia-0.8.0-beta
$ ls .vscode/extensions/julialang.language-julia-0.8.0-beta/
CHANGELOG.md              LICENSE.txt   out           scripts
images                    media         package.json  snippets
julia.configuration.json  node_modules  README.md     syntaxes
$ ls .vscode/extensions/julialang.language-julia-0.8.0-beta/out/src/
extension.js  repl.js  weave.js
$ ls .vscode/extensions/julialang.language-julia-0.8.0-beta/node_modules/
async-child-process    inherits          pseudomap
async-file             isexe             q
babel-runtime          lru-cache         regenerator-runtime
balanced-match         minimatch         rimraf
brace-expansion        minimist          temp
child-process-promise  mkdirp            vscode-jsonrpc
concat-map             ms                vscode-languageclient
core-js                node-version      vscode-languageserver-types
cross-spawn            once              which
debug                  os-tmpdir         wrappy
fs.realpath            path-is-absolute  yallist
glob                   promised-temp
inflight               promise-polyfill
```

**Comment by chriselrod** [comment]
This was user error, not a bug in VSCode:
https://discourse.julialang.org/t/vs-code-extension-v0-8-0-beta-1-release/6124/9?u=elrod

Feel free to close this.
