### ISSUE TITLE
spurious Possible use of undeclared variable

### ISSUE THREAD

**Issue by lewisl** [JuliaEditorSupport/julia-vscode#478]
As follows:

using DataFrames  # this is a popular module

....   later in a function:

deleterows!(housetable, findin(housetable[:District], nonvote))

deleterows! is a function in module DataFrames

It is flagged by linter:  Possible use of undeclared variable DataFrame

This occurs for every function in module DataFrames.

MacOS 10.13.3
Visual Studio Code 1.21.1
julia-vscode 0.9.1

Guess I'll turn off the linter for now!

**Comment by ZacLN** [comment]
fixed on master

**Comment by lewisl** [comment]
Progress!

How do I load into VSCode?

**Comment by davidanthoff** [comment]
We're going to release alpha and beta versions [here](https://github.com/JuliaEditorSupport/julia-vscode/releases). Probably easiest to grab the vsix files from there and go with that.

**Comment by lewisl** [comment]
Got it.

**Comment by davidanthoff** [comment]
Should in theory work with 0.7, but I'm not sure.

We also might have a bug with crash reporting currently, so would be great if you could try again once we've fixed that.

**Comment by lewisl** [comment]
Will do.

**Comment by davidanthoff** [comment]
https://discourse.julialang.org/t/vs-code-extension-v0-11-0-beta-release/17541

That would be the version to try!

**Comment by lewisl** [comment]
The Julia language extension crashed.  OK’ed sending the crash report.

The language server crashes.

Anything I should do from a config standpoint?  I am running 0.7.  l still have some code from an older project that I should check with deprecation warnings before switching to 1.0x

**Comment by davidanthoff** [comment]
Sending crash reports is the best thing right now...
